import os
import json
import docx
import PyPDF2
import pptx
from flask import Flask, render_template, request, jsonify, session, redirect, url_for, flash
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from dotenv import load_dotenv
from functools import wraps
from datetime import datetime, timedelta
from authlib.integrations.flask_client import OAuth
import google.generativeai as genai
import base64

load_dotenv(override=True)
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

# Disable SSL verification globally for local environment issues
import requests
from urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)
# Monkeypatch requests to default to verify=False
_orig_request = requests.Session.request
def _new_request(self, *args, **kwargs):
    kwargs['verify'] = False
    return _orig_request(self, *args, **kwargs)
requests.Session.request = _new_request

os.environ['SSL_CERT_FILE'] = ''
os.environ['REQUESTS_CA_BUNDLE'] = ''

app = Flask(__name__)
app.secret_key = os.getenv("SECRET_KEY", "dev-secret-key")
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///users.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['MAX_CONTENT_LENGTH'] = 100 * 1024 * 1024 # 100MB Limit
app.permanent_session_lifetime = timedelta(days=30)

db = SQLAlchemy(app)

# Models
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    analyses = db.relationship('Analysis', backref='owner', lazy=True)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

class Analysis(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    source = db.Column(db.String(200), nullable=False)
    probability = db.Column(db.String(10), nullable=False)
    explanation = db.Column(db.Text, nullable=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

with app.app_context():
    db.create_all()

# OAuth Configuration
oauth = OAuth(app)
google = oauth.register(
    name='google',
    client_id=os.getenv("GOOGLE_CLIENT_ID"),
    client_secret=os.getenv("GOOGLE_CLIENT_SECRET"),
    server_metadata_url='https://accounts.google.com/.well-known/openid-configuration',
    jwks_uri='https://www.googleapis.com/oauth2/v3/certs',
    client_kwargs={'scope': 'openid email profile'}
)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") or os.getenv("OPENAI_API_KEY")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "admin@example.com")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "Admin123")

def extract_text_from_file(file, filename):
    text = ""
    ext = filename.rsplit('.', 1)[1].lower()
    
    try:
        if ext == 'txt':
            text = file.read().decode('utf-8')
        elif ext == 'pdf':
            pdf_reader = PyPDF2.PdfReader(file)
            for page in pdf_reader.pages:
                extracted = page.extract_text()
                if extracted:
                    text += extracted + "\n"
        elif ext == 'docx':
            doc = docx.Document(file)
            for para in doc.paragraphs:
                text += para.text + "\n"
        elif ext == 'pptx':
            prs = pptx.Presentation(file)
            for slide in prs.slides:
                for shape in slide.shapes:
                    if hasattr(shape, "text"):
                        text += shape.text + "\n"
    except Exception as e:
        print(f"Error extracting text from {ext}: {e}")
    
    return text.strip()

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY, transport='rest')

def analyze_multimodal(content_parts):
    if not GEMINI_API_KEY:
        return {"error": "Gemini API key not found."}
    
    # genai.configure already done above
    
    system_prompt = """
    You are an expert AI Detection system. Your task is to analyze the provided content (text, image, or video) 
    and determine if it was generated by an AI (e.g., GPT, DALL-E, Midjourney, Sora, Runway, Pika, Invideo, Instudio, HeyGen, etc.).
    
    CRITICAL WATERMARK CHECK: Before analyzing anything else, strictly scan the edges and corners of the image or video for any watermarks, logos, or text indicating an AI generation tool (e.g., "Invideo", "Instudio", "Runway", "Pika", "HeyGen", "D-ID", "Synthesia"). If ANY such watermark is present, the probability MUST be 100% AI-generated, regardless of how realistic the footage looks.
    
    If it is an image: Look for common AI artifacts like unnatural textures, extra fingers, warped details, or deepfake patterns.
    If it is a video: Pay strict attention to temporal inconsistencies, morphing objects, unnatural physics, flickering, weird background distortions, and lack of object permanence across frames. These are very strong indicators of AI video generation.
    If it is text: Look for linguistic patterns, perplexity, and burstiness common in LLMs.
    
    Return the response ONLY as a JSON object with the following keys exactly:
    - "probability": "XX%" (string, representing the probability that the content is AI-GENERATED. 0% means definitely human, 100% means definitely AI)
    - "pattern_consistency": "A short sentence describing repetitive patterns or lack thereof."
    - "structural_integrity": "A short sentence describing visual/logical cohesion, temporal consistency, and potential warping/hallucination."
    - "noise_signature": "A short sentence describing artifacts, blur, semantic noise, or flickering."
    - "metadata_validation": "A short sentence checking for AI WATERMARKS and assessing authenticity markers."
    - "explanation": "A concise expert analysis summary detailing exactly why this is human or AI. Explicitly mention if a watermark was found."
    """
    
    # Use 2.5-flash directly as it is supported and lightning fast
    models_to_try = ['gemini-flash-latest', 'gemini-2.0-flash']
    
    os.environ['SSL_CERT_FILE'] = ''
    os.environ['REQUESTS_CA_BUNDLE'] = ''
    
    for model_name in models_to_try:
        try:
            model = genai.GenerativeModel(model_name, generation_config={"response_mime_type": "application/json"})
            response = model.generate_content([system_prompt] + content_parts)
            
            # Robust JSON extraction
            raw_text = response.text.strip()
            if raw_text.startswith("```json"):
                raw_text = raw_text.split("```json")[1].split("```")[0].strip()
            elif raw_text.startswith("```"):
                raw_text = raw_text.split("```")[1].split("```")[0].strip()
                
            return json.loads(raw_text)
        except Exception as e:
            print(f"Model {model_name} failed: {e}")
            continue
            
    return {"error": "AI analysis failed. Please try again with a smaller file or different format."}

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in session:
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated_function

@app.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        if password != confirm_password:
            flash('Passwords do not match', 'error')
            return redirect(url_for('signup'))
        
        import re
        # Strong password regex: 8+ chars, 1 uppercase, 1 lowercase, 1 number, 1 special character
        if not re.match(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$", password):
            flash('Password must be at least 8 characters long, contain an uppercase letter, a lowercase letter, a number, and a special character.', 'error')
            return redirect(url_for('signup'))
            
        if User.query.filter_by(email=email).first():
            flash('Email already registered', 'error')
            return redirect(url_for('signup'))
        new_user = User(email=email)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()
        flash('Account created! Please log in.', 'success')
        return redirect(url_for('login'))
    return render_template('signup.html')


@app.route('/login', methods=['GET'])
def login():
    return render_template('login.html')

@app.route('/login/basic', methods=['POST'])
def login_basic():
    email = request.form.get('email')
    password = request.form.get('password')
    user = User.query.filter_by(email=email).first()
    if (user and user.check_password(password)) or (email == ADMIN_EMAIL and password == ADMIN_PASSWORD):
        session['user'] = {'email': email}
        session.permanent = True
        return redirect(url_for('dashboard'))
    flash('Invalid email or password', 'error')
    return redirect(url_for('login'))


@app.route('/login/google')
def google_login_route():
    try:
        redirect_uri = url_for('google_authorize_route', _external=True)
        return google.authorize_redirect(redirect_uri)
    except Exception as e:
        return f"Login Error: {str(e)}", 500

@app.route('/login/google/authorize')
def google_authorize_route():
    try:
        token = google.authorize_access_token()
        user_info = token.get('userinfo')
        if user_info:
            email = user_info.get('email')
            user = User.query.filter_by(email=email).first()
            if not user:
                user = User(email=email)
                user.set_password(os.urandom(16).hex())
                db.session.add(user)
                db.session.commit()
            session['user'] = user_info
            session.permanent = True
        return redirect(url_for('dashboard'))
    except Exception as e:
        flash(f"Google Login failed: {str(e)}")
        return redirect(url_for('login'))

@app.route('/history')
@login_required
def history():
    user = User.query.filter_by(email=session['user']['email']).first()
    if not user:
        user_history = []
    else:
        user_history = Analysis.query.filter_by(user_id=user.id).order_by(Analysis.timestamp.desc()).all()
    return render_template('history.html', history=user_history)

@app.route('/history/clear', methods=['POST'])
@login_required
def clear_history():
    user = User.query.filter_by(email=session['user']['email']).first()
    if user:
        Analysis.query.filter_by(user_id=user.id).delete()
        db.session.commit()
        flash('History cleared successfully.')
    return redirect(url_for('history'))

@app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('landing'))

@app.route('/')
def landing():
    # If user is already logged in, skip landing page and go straight to dashboard
    if 'user' in session:
        return redirect(url_for('dashboard'))
    return render_template('landing.html')

@app.route('/dashboard')
@login_required
def dashboard():
    user = User.query.filter_by(email=session['user']['email']).first()
    is_new_user = True
    if user:
        history_count = Analysis.query.filter_by(user_id=user.id).count()
        is_new_user = (history_count == 0)
    return render_template('index.html', is_new_user=is_new_user)

@app.route('/analyze', methods=['POST'])
@login_required
def analyze():
    content_parts = []
    source_name = "Pasted Text"
    
    try:
        if 'text' in request.form and request.form['text'].strip():
            content_parts.append(request.form['text'].strip())
        elif 'file' in request.files:
            file = request.files['file']
            if file.filename != '':
                source_name = file.filename
                mime_type = file.content_type
                
                # Check file size (Gemini API limit is around 20MB for inline data)
                file.seek(0, os.SEEK_END)
                file_size = file.tell()
                file.seek(0)
                
                if file_size > 100 * 1024 * 1024: # 100MB limit
                    return jsonify({"error": "File too large. Please upload files under 100MB."}), 400
                
                # Text-based documents (Word, PPT, TXT)
                if mime_type in ['text/plain', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.presentationml.presentation']:
                    text = extract_text_from_file(file, file.filename)
                    if text: content_parts.append(text)
                    else: return jsonify({"error": "Could not extract text from document."}), 400
                
                # Images, Videos, & PDFs (Multimodal)
                elif mime_type.startswith('image/') or mime_type.startswith('video/') or mime_type == 'application/pdf':
                    if mime_type.startswith('video/'):
                        print(f"Extracting frames from video to bypass slow File API...")
                        temp_path = f"temp_{file.filename}"
                        file.save(temp_path)
                        
                        try:
                            import cv2
                            cap = cv2.VideoCapture(temp_path)
                            total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
                            frames_to_extract = 5 # Extract fewer frames for extreme speed
                            
                            if total_frames > 0:
                                step = max(1, total_frames // frames_to_extract)
                                for i in range(frames_to_extract):
                                    frame_id = int(i * step)
                                    if frame_id >= total_frames: break
                                    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_id)
                                    ret, frame = cap.read()
                                    if ret:
                                        # Downscale frame for hyper-fast inference and smaller payload
                                        h, w = frame.shape[:2]
                                        max_dim = 640
                                        if max(w, h) > max_dim:
                                            scale = max_dim / max(w, h)
                                            frame = cv2.resize(frame, (int(w * scale), int(h * scale)))
                                            
                                        _, buffer = cv2.imencode('.jpg', frame, [int(cv2.IMWRITE_JPEG_QUALITY), 60])
                                        content_parts.append({
                                            "mime_type": "image/jpeg",
                                            "data": base64.b64encode(buffer).decode('utf-8')
                                        })
                            cap.release()
                        except Exception as e:
                            print(f"Frame extraction failed: {e}")
                            return jsonify({"error": "Failed to extract video frames."}), 500
                        finally:
                            if os.path.exists(temp_path): os.remove(temp_path)
                            
                    elif mime_type == 'application/pdf' and file_size > 10 * 1024 * 1024:
                        print(f"Using File API for large PDF ({file_size} bytes)...")
                        temp_path = f"temp_{file.filename}"
                        file.save(temp_path)
                        uploaded_file = genai.upload_file(path=temp_path, display_name=file.filename)
                        
                        import time
                        while uploaded_file.state.name == "PROCESSING":
                            time.sleep(2)
                            uploaded_file = genai.get_file(uploaded_file.name)
                        
                        if uploaded_file.state.name == "FAILED":
                            return jsonify({"error": "AI file processing failed."}), 500
                            
                        content_parts.append(uploaded_file)
                        if os.path.exists(temp_path): os.remove(temp_path)
                    else:
                        if mime_type.startswith('image/'):
                            from PIL import Image
                            import io
                            img = Image.open(file)
                            if img.mode != 'RGB': img = img.convert('RGB')
                            img.thumbnail((800, 800)) # Compress for extreme speed
                            img_byte_arr = io.BytesIO()
                            img.save(img_byte_arr, format='JPEG', quality=75)
                            file_bytes = img_byte_arr.getvalue()
                            mime_type = "image/jpeg"
                        else:
                            file_bytes = file.read()
                            
                        content_parts.append({
                            "mime_type": mime_type,
                            "data": base64.b64encode(file_bytes).decode('utf-8')
                        })
                else:
                    return jsonify({"error": f"Unsupported file type: {mime_type}"}), 400

        if not content_parts:
            return jsonify({"error": "No content provided."}), 400
            
        result = analyze_multimodal(content_parts)
        
        if "error" in result:
            return jsonify(result), 500
            
        # Save to Database
        user = User.query.filter_by(email=session['user']['email']).first()
        if user:
            new_analysis = Analysis(
                user_id=user.id,
                source=source_name,
                probability=result.get("probability", "0%"),
                explanation=json.dumps(result)  # Store full JSON for advanced reporting
            )
            db.session.add(new_analysis)
            db.session.commit()
            
        return jsonify(result)
    except Exception as e:
        print(f"Internal Server Error in /analyze: {e}")
        return jsonify({"error": f"Internal Server Error: {str(e)}"}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True)
